name: Lean CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lean toolchain
        uses: leanprover/lean-action@v1
        with:
          auto-config: false
          build: false
          test: false
          lint: false

      - name: Resolve dependencies
        run: lake update

      - name: Build
        run: lake build
